FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libatlas-base-dev \
    libboost-all-dev \
    libarpack++2-dev \
    cmake \
    git \
    python3 \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]